### ISSUE TITLE
Member Activity Evaluation Record / Progress Record

### ISSUE THREAD

**Issue by tomonsoejang** [vigneshm-quikieapps/risign-stars-backend#16]
## Todo

- [ ] add a progress record of a student in an activity
- [ ] get a progress record of a student in an activity
- [ ] mark a skill as in progress/ attained
- [ ] add the in progress date (when marking the status of skill as in progress)
- [ ] add the attained date (when marking the status of skill as attained)
