### ISSUE TITLE
Parent Management

### ISSUE THREAD

**Issue by tomonsoejang** [vigneshm-quikieapps/risign-stars-backend#19]
### Add Child and Emergency Contacts
- [x] add contact details of child, emergency contact (primary), emergency contact (secondary)
- [x] update
- [x] get ~~child/student~~ member emergency contacts
- [x] delete. (check if student/child is enrolled in any class, then deleting is not allowed)

## Activity selection
- [x] Enrol a student/child in a class/session (mentioned in #10)

### Fees 
- [x] get course charges of a particular class (fetching class contains charges, mentioned in #9 )

### member consent / provide consent
- [x] get student consent (mentioned in #10 )
- [x] add student consent (mentioned in #10 )

### Additional Section
- [x] #35

### Change Class / Class Transfer (mentioned in #10)
- [x] class transfer of a student from one class to another.

### Cancel the membership (mentioned in #10)
- [x] cancel the membership of a student from a class/ an activity

**Comment by tejfaster** [comment]
Crud Api Child done

**Comment by tejfaster** [comment]
validator, controller, route all these are completed

**Comment by tejfaster** [comment]
Arun you have to work on schema  for additional information like consent, Emergency, Activity

**Comment by arunsaras** [comment]
Additional section(email,sms,telephone) will be covered while enrolling a child in a session/class API

**Comment by tomonsoejang** [comment]
@sudarshanshkrishna  Please make sure the Add Child and Emergency Contacts API's are working fine. Thanks.
