### ISSUE TITLE
Implement Role Based Authentication Control

### ISSUE THREAD

**Issue by tomonsoejang** [vigneshm-quikieapps/risign-stars-backend#33]
### Todo
- [x] Super admin access
- [x] Business Administrator access
- [x] Coach access
- [x] User access
- [x] create isAuthorized() middleware to check for authentication and authorization
- [x] isAuthorized(null, null), should allow all users with the Bearer token.
- [x] implement getResourceBusinessId() method for each route where Business Admin Access is required. e.g of the function for create class route. 
```
const getResourceBusinessId = async (res) => {
  let { classId } = req.body
  let businessClass = await BusinessClass.findById(classId)
  return businessClass.businessId
}
```
- [x] isAuthorized(page, action, { getResourceBusinessId }) should allow a user that has permission for that particular page. e.g: isAuthorized(CLASS_DEFINITION, CREATE, { getResourceBusinessId })
- [x] implement isAuthHandler for each route where parent access should be allowed. 
```
e.g.
isAuthHandler for updating a member by a parent

const isAuthHandler = (req) => {
  let {memberId} = req.body
  let member = await Member.findById(memberId)
  let {authUserData} = req
  return authUserData.id === member.userId
}
```
- [x] isAuthorized(null, null, { isAuthHandler }) should allow parent only.

- [x] isAuthorized(page, action, {getResourceBusinessId, isAuthHandler}) should allow a user that has permission for that particular page or allow a parent only.
- [x] integrate into all endpoints wherever required.
- [x] implement super admin

**Comment by sudarshanshkrishna** [comment]
completed all tasks
